const screenName = {
  authStackNavigator: 'authStackNavigator',
  mainStackNavigator: 'mainStackNavigator',
  mainTabNavigator: 'mainTabNavigator',

  splashScreen: 'splashScreen',
  homeScreen: 'homeScreen',
  searchScreen: 'searchScreen',
  categoryScreen: 'categoryScreen',
  notifyScreen: 'notifyScreen',
  bookcaseScreen: 'bookcaseScreen',
  forumScreen: 'forumScreen',
  forumScreen: 'forumScreen',
  profileScreen: 'profileScreen',
  newsFeedScreen: 'newsFeedScreen',
  comicScreen: 'comicScreen',
  rankingScreen: 'rankingScreen',
  channelScreen: 'channelScreen',
  pointMeScreen: 'pointMeScreen',
  dailyScreen: 'dailyScreen',
  buyCoinScreen:'buyCoinScreen',
  detailChapter:'detailChapter',
  detailScreen: 'detailScreen',
  filterScreen: 'filterScreen',

  movieScreen: 'movieScreen',
  aboutScreen: 'aboutScreen',
  chapterScreen: 'chapterScreen',
  commentScreen: 'commentScreen',
  dailyAttendanceScreen: 'dailyAttendanceScreen',
  downloadScreen: 'downloadScreen',
  followScreen: 'followScreen',
  forumTabScreen: 'forumTabScreen',
  gameScreen: 'gameScreen',
  historyScreen: 'historyScreen',
  novelScreen: 'novelScreen',
  shortStoryScreen: 'shortStoryScreen',
  chatStoryScreen: 'chatStoryScreen',
  writeStoryScreen: 'writeStoryScreen',

  signinScreen: 'SignInScreen',
  signupScreen: 'SignUpScreen',
  updateProfile:'updateProfile',
  forgotPassScreen: 'forgotPassScreen',
  changePassScreen: 'changePassScreen',
  MainTab: 'MainTab',
}

export default screenName

